//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_Agencia_Viajes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class API_AgenciaViajesDB : DbContext
    {
        public API_AgenciaViajesDB()
            : base("name=API_AgenciaViajesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Viajeros> Viajeros { get; set; }
        public virtual DbSet<Viajeros_Viajes> Viajeros_Viajes { get; set; }
        public virtual DbSet<Viajes_Disponibles> Viajes_Disponibles { get; set; }
    
        public virtual ObjectResult<SP_Traer_Viajeros_Viajes_Result> SP_Traer_Viajeros_Viajes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Traer_Viajeros_Viajes_Result>("SP_Traer_Viajeros_Viajes");
        }
    }
}
