//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_Agencia_Viajes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viajes_Disponibles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viajes_Disponibles()
        {
            this.Viajeros_Viajes = new HashSet<Viajeros_Viajes>();
        }
    
        public int ID_Viajes_Disponibles { get; set; }
        public string COD_Viaje { get; set; }
        public int NUM_Plazas { get; set; }
        public string Lugar_Origen { get; set; }
        public string Lugar_Destino { get; set; }
        public decimal Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viajeros_Viajes> Viajeros_Viajes { get; set; }
    }
}
